### ISSUE TITLE
Class weights

### ISSUE THREAD

**Issue by tonyjhlam** [LukeLB/LogisticRegression_Firth#1]
Is there a way to provide class weights to account for class imbalance?

**Comment by LukeLB** [comment]
Unfortunatley not in my implementation. Maybe I'm getting confused here but, isn't the Firth corrected MLE there to account for the class imbalance?

**Comment by tonyjhlam** [comment]
I thought so as well, but if you look at the R implementation, they still have a weights parameter (https://www.rdocumentation.org/packages/logistf/versions/1.24.1/topics/logistf). Looking into the literature, they emphasize a lot about Firth's ability to handle small sample bias and ability to converge even in cases of complete separation, but I don't see anything about class imbalance. So my assumption was that the small sample bias is an entirely different issue compared to bias coming from class imbalance. I am not familiar with the theorem behind this method, so maybe I am confusing myself.

**Comment by LukeLB** [comment]
Although not literature sources these two links provide examples of people suggesting Firth regression for imbalanced data sets:
- https://medium.com/datadriveninvestor/firths-logistic-regression-classification-with-datasets-that-are-small-imbalanced-or-separated-49d7782a13f1 
- https://stats.stackexchange.com/questions/441443/unbalanced-data-with-logistic-regression-good-references

Using class weighting may be an additional way to fight against class imbalance but I personally don't have any experience with it. All I can say is when I was using this code in a project I tried using standard logistic regression on my imbalanced data set and it would not converge but this Firth formulation did.

**Comment by tonyjhlam** [comment]
Probably is another method to handle the imbalance, I noticed that in some of the R implementation examples, they sometimes use the weights parameter. Thanks for the discussion and quick response.
